<?xml version="1.0"?>

<!-- Inline DTD for the XML below-->
<!DOCTYPE games [
    <!ELEMENT games (game*)>
    <!ELEMENT game (home-team, ex-team, scores, yellows, reds)>
    <!ATTLIST game score CDATA #REQUIRED>
    <!ELEMENT home-team (#PCDATA)>
    <!ELEMENT ex-team (#PCDATA)>
    <!ELEMENT scores (score+)>
    <!ELEMENT score (player+)>
    <!ATTLIST score
        me CDATA #REQUIRED
        type (field | penalty) #IMPLIED
    >
    <!ELEMENT player (#PCDATA)>
    <!ELEMENT yellows (player+)>
    <!ELEMENT reds (player+)>
]>

<games>
    <game score="1-1">
        <home-team>Roma</home-team>
        <ex-team>Lazio</ex-team>
        <scores>
            <score me="15">
                <player>Klose</player>
            </score>
            <score me="85" type="penalty">
                <player>Tox</player>
            </score>
        </scores>
        <yellows>
            <player>Tox</player>
            <player>Hernanes</player>
        </yellows>
        <reds>
            <player>Kjaer</player>
        </reds>
    </game>
</games>